# Generated by Django 5.2.7 on 2026-04-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
