# Generated by Django 5.2.7 on 2026-05-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_remove_project_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
